### ISSUE TITLE
Blog posts not working

### ISSUE THREAD

**Issue by nunobrito** [triplecheck/triplecheck.github.io#2]
The link for the blog posts goes to nowhere. I will need two things for the blog:

1) A page where the blog posts will be listed
2) A template that I can use for placing the blog contents

For 2), I helps to use an example that has images. On the original design the posts didn't look good whenever an image was added. Would be good to sort this issue on the new edition.

Here is an example of post with images that can be used: http://nunobrito1981.blogspot.de/2014/11/looking-into-net-license-compliance.html

**Comment by fdvenk** [comment]
I don't see blog post page in current website. Is that new page will be added in current build? please confirm.

**Comment by fdvenk** [comment]
I've removed form as requested. And I need mail ID to replace it. Currently it is empty. Please share the mail ID asap.

**Comment by nunobrito** [comment]
The email is contact@triplecheck.de

Pleased look on the code that was overwritten for the contact and download pages. Also, I'd ask to please restore the codie logo so we can have the site on a more finished state.

**Comment by fdvenk** [comment]
The recent writing form replaced with mail link. And, I have replaced code which you have pushed initially. In that, I don't see differentiation between my structure and your initial structure. Can you zip it and send your code. So that, I will replace it.

**Comment by nunobrito** [comment]
Don't worry. I applied the changes this morning:
- Codie logo fixed (see link to see how it changed)
- Removed "add writing" button.
- Removed form from contact page, added the email

You can see what changed here:
https://github.com/triplecheck/triplecheck.github.io/commit/df8c1101b66545f950aeffa354ee0ed2ca5a63e4

Type "git pull" to get these changes on your side. I'm making some minor changes on the content so we can get the site ready for public.

**Comment by nunobrito** [comment]
btw. We still need a template for writing blog posts and page where these blogs can be listed. To recall, this is called "writings" on the front page, so we are taking care of the part that shows users the content for these articles.
