### ISSUE TITLE
Resolution on cellphones

### ISSUE THREAD

**Issue by nunobrito** [triplecheck/triplecheck.github.io#3]
The site should be comfortable for cellphones, especially when viewed from portrait mode.

On thing to consider is minimum support for the Opera navigator for Android, it is popular because it makes pages load with less network bandwidth but disables Javascript effects. On our case we don't need to aim 100% for this kind of browser but it is needed to test and make sure that people can still navigate using this browser. This was possible on the first version.

**Comment by fdvenk** [comment]
In my implementation, I don't use javascript for responsiveness to mobile browsers. It could work well without javascript in all mobile browsers.

**Comment by fdvenk** [comment]
I have implemented menu portion responsiveness for 480 pixel resolution

**Comment by fdvenk** [comment]
Homepage responsiveness done for homepage.

**Comment by fdvenk** [comment]
All pages responsiveness done for mobile sizes
