### ISSUE TITLE
Missing styling for bullets

### ISSUE THREAD

**Issue by nunobrito** [triplecheck/triplecheck.github.io#4]
The following text "test" doesn't have the same text style as normal text inside the blog posts:
```
<ul>
   <li>test</li>
</ul>
```
We're missing a CSS rule for them.

**Comment by nunobrito** [comment]
This is still not fixed, here is an example: http://triplecheck.net/blog/non-obvious-GPL.html

**Comment by fdvenk** [comment]
fixed
