### ISSUE TITLE
Website header different when going from front-page to blog page

### ISSUE THREAD

**Issue by nunobrito** [triplecheck/triplecheck.github.io#6]
Try opening the main page, then click on the blog link at the footer while looking at the triplecheck logo.

The logo will move. The header is different when going from any page on the root of the site to the blog pages.

This should be corrected.

**Comment by fdvenk** [comment]
It happening because of the homepage has scroll to view more content and blog page doesn't have much content to scroll. when scroll bar hiding off, this could happened.

**Comment by rilwal** [comment]
Fixed this, as well as the footer being in the wrong place by putting a minimum height on #body divs.
932bd27

**Comment by rilwal** [comment]
Note, you might have to clear your cache to get the new CSS to apply, I did.

**Comment by nunobrito** [comment]
Ok. Looking on the demo page when going back and forth now the position of the header is equal but the font changes. 

@rilwal Can we have the same font at the demo page?

**Comment by rilwal** [comment]
I fixed the font. The header still looks slightly different on the demo page, I can't figure out why at this stage. I suspect bootstrap or another CSS file is interfering. Will investigate further.

**Comment by rilwal** [comment]
I opened a new issue for the new problem #8.
