### ISSUE TITLE
Demo page: When adding files for the first time, loading page doesn't stop

### ISSUE THREAD

**Issue by nunobrito** [triplecheck/triplecheck.github.io#7]
Steps to reproduce this defect:

- Load page from incognito session
- Add files with some license references inside
- Number of files is updated but processing dialog does not go away
- Only starts working when end-users clicks on a file at the tree view

As note:
- I am dropping the files with licenses that you find at https://github.com/triplecheck/3mark/tree/master/run/archive_licenses
- Chrome on my side is version 35.0

**Comment by nunobrito** [comment]
I see improvement. The progress bar is now gone after dropping files but the graph just appears after I click at one of the files on the tree view.

**Comment by rilwal** [comment]
I think it's fixed now, can you confirm?

**Comment by nunobrito** [comment]
Hooray! :+1: 

It is working!
